### ISSUE TITLE
Provide solution for FadeMode.FromStart to use it with Mixers also

### ISSUE THREAD

**Issue by Dukobpa3** [KybernetikGames/animancer#224] opened 2022-09-07 08:45 UTC
# Use Case

Now I can define FadeMode.FromStart only with ClipState.
But there is couple cases when I wanted to use FromStart Mixers also.
E.g. JumpStart animation. I have Mixer with different JumpStartFromIdle/JumpStartFromRun/JumpStartUp/JumpStartForward clips.
All jumpStart animations started from little crouch then push up.
When using any other FadeMode – this starting details like crouch and push loosing while transitioning. But also if I make transition shorter – it looks like two different animations Move->Jump with twitching between them.

# Solution

I understand the reasons why FadeMode.FromStart declined for mixer. I think it because not clear how to get first frame of Mixer. Since we passing Parameters just after starting State – it is actually processing at least in the 2-nd frame.

But for this case we can use some "default" mixed first frame made from all Clips of Mixer.
Or we can recalculate "First Frame" in the each frame while transitioning, accordingly to passed parameters.
Or we can add ability to describe Mixer Parameters in the transition before start, or pass this parameters to _animancer.Play() method. Or something like that.

# Alternatives

Thats the question. Maybe someone can suggest any workaround about that.

**Comment by KybernetikGames** [comment] 2022-09-07 09:36
> I understand the reasons why FadeMode.FromStart declined for mixer. I think it because not clear how to get first frame of Mixer. Since we passing Parameters just after starting State – it is actually processing at least in the 2-nd frame.

That's not a problem, the parameter is just used to calculate the `Weight` of each state, which is entirely separate from their `Time`.

The real problem is that `FadeMode.FromStart` works by creating a duplicate of the original state, leading to two issues:

- The performance cost of creating a Mixer and potentially many child states (which could also be nested mixers) is much more significant than the cost of creating just one state. Obviously that isn't actually preventing the feature from being implemented, but it would be a hidden risk behind something that seems to just work.
- Your code will generally only be controlling one mixer so anything that keeps a reference to it will still be controlling the original even after a duplicate is created so it would look like the parameter has stopped working. That would get even worse with nested mixers.

# Alternatives

In general, the approach I'd recommend is to just make an array of mixers on startup, pick the one with the lowest weight when you want to play it, and always set all their parameters at the same time.

In your case, "JumpStartFromIdle/JumpStartFromRun/JumpStartUp/JumpStartForward" sound like you'd essentially want to pick one when it starts and let it play, in which case you don't need a mixer at all. You could just put them all in an array as individual clips/transitions and play the appropriate one as necessary.

Otherwise, the actual implementation wouldn't be particularly difficult as long as you're using a transition to define your mixer:

1. Go to `AnimancerLayer.cs` and make a copy of the `GetOrCreateWeightlessState` method.
2. Change its parameter to `ITransition transition`.
3. Add the following line at the start before the `if`: `var state = layer.GetOrCreateState(transition);`
4. Replace `state = Root.States.GetOrCreate((object)state, clip);` with this:

```
var key = (object)state;
if (!layer.Root.States.TryGet(key, out state))
{
    state = transition.CreateStateAndApply(layer.Root);
    state.Key = key;
}
```

Getting it to work automatically with `FadeMode.FromStart` would be much more complicated, but that should let you achieve the same result by doing this:

```
var state = animancer.Layers[0].GetOrCreateWeightlessState(mixerTransition);
animancer.Play(state, mixerTransition.FadeDuration);
mixerTransition.Apply(state);
state.Time = 0;
```

I haven't actually tested that, so let me know how it goes. If it works and you don't run into issues with controlling the parameters of the wrong duplicate, I'll consider adding it to the next version.

**Comment by Dukobpa3** [comment] 2022-09-07 09:51
I'll try and give some feedback after

**Comment by Dukobpa3** [comment] 2022-09-07 15:36
Works as expected.
I've not tested about memory usage accordingly to new copies etc. But logic and behaviour is ok.

I don't have any issues with setting parameters because using it this way(each time saving current running state):
```csharp
        public UniTask StartAnimation(ITransition next) => StartAnimation(next, 1f);

        public UniTask StartAnimation(ITransition next, bool fromStart)
        {
            _cts = new CancellationTokenSource();
            Previous = _animancer.States.Current;

            Current = _animancer.Layers[0].GetOrCreateWeightlessState(next);
            _animancer.Play(Current, next.FadeDuration);
            next.Apply(Current);
            Current.Time = 0;

            _animationsState[Current] = false;
            Current.Events.OnEnd += OnAnimationEnd;

            return UniTask
                  .WaitUntil(() => !_animancer.Animator.IsInTransition(0), cancellationToken: _cts.Token)
                  .SuppressCancellationThrow();
        }

        public UniTask StartAnimation(ITransition next, float coefficient)
        {
            _cts = new CancellationTokenSource();
            Previous = _animancer.States.Current;
            Current = _animancer.Play(next);
            Current.Speed *= coefficient;
            _animationsState[Current] = false;
            Current.Events.OnEnd += OnAnimationEnd;

            return UniTask
                  .WaitUntil(() => !_animancer.Animator.IsInTransition(0), cancellationToken: _cts.Token)
                  .SuppressCancellationThrow();
        }
```

**Comment by Dukobpa3** [comment] 2022-09-07 15:52
But in this implementation we are always using "Weightless" state.

In my case with jump – I've lost all variants except "Idle in first frame".

Looks better than before, but I want to see different starts, like FromIdle/FromStep/FromRun etc.
They all already merged into my Mixer and worked before accordingly to Mixer Parameters.

**Comment by Dukobpa3** [comment] 2022-09-07 15:54
I have Two main Mixers
– Move – Idle/Step/Run/FastRun
– JumpStart – FromIdleUp/FromIdleForward/FromRunForward

And trying make transition between them.
Working great in general, except described issues.

**Comment by Dukobpa3** [comment] 2022-09-07 16:14
Great!

And also I passing MixerParameters just after starting transition and it is working also.

```csharp
        public UniTask Enter(MotionTransition from, ImpactData source)
        {
            if (source != null)
            {
                _exitImpact = source;
                Impact.Velocity = source.Velocity;
            }

            Assert.IsNotNull(Transition, $"Wrong transition mapping for state: {StateId}");
            Transition.FadeDuration = from.FadeDuration;

            Transition.Events.SetCallback(Events.JUMP, OnJumpStarted);

            var task = Animator.StartAnimation(Transition, true);
            Animation.Parameter = CharacterData.VelocityH; // <––-

            return task;
        }

```

**Comment by KybernetikGames** [comment] 2022-09-08 02:50
Glad to hear it works. I'll put it on my list of things to add properly in the next version.

`_animancer.Animator.IsInTransition(0)` won't work with Animancer because it only knows about transitions inside Animator Controllers. You could instead check `Current.Weight != Current.TargetWeight`.

**Comment by Dukobpa3** [comment] 2022-12-10 15:53
Would you describe what was changed in the code?
Because I've implemented it in my code in the way you've suggested. And maybe will be some conflicts after update?

**Comment by KybernetikGames** [comment] 2022-12-10 22:19
Quite a lot of things have changed internally. Big changes in `AnimancerLayer`. All states now have a `Clone` method. And Mixers have completely changed the way they manage child states to support the simplified initialization syntax.

But externally, the changes are pretty simple. You should basically be able to use `FadeMode.FromStart` exactly as you were expecting originally.

**Comment by Dukobpa3** [comment] 2022-12-11 11:28
So I'll discard my changes before update.
Thanks.

**Comment by KybernetikGames** [comment] 2023-01-26 04:20
[Animancer v7.4](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-4/) is now available with mixer cloning.

**Closed by KybernetikGames** 2023-01-26 04:20 UTC
Labels: Enhancement, Solved
