### ISSUE TITLE
Play a animtionClip and a ClipTransition in different layers in same frame

### ISSUE THREAD

**Issue by NiyahIsFine** [KybernetikGames/animancer#232] opened 2022-11-14 11:49 UTC
the first layer donest work, it awlays plays the second layer's anim;

**Comment by KybernetikGames** [comment] 2022-11-14 12:35
The [Dynamic Layers](https://kybernetik.com.au/animancer/docs/examples/layers/dynamic/) example demonstrates how to play one animation on two different layers at the same time.

I can't really give any specific advice without more information.

**Comment by NiyahIsFine** [comment] 2022-11-15 07:49
AnimationClip animationClip;
ClipTransition clipTransition;


_Layer1.Play(animationClip);
_Layer2.Play(clipTransition); 
   or
_Layer1.Play(clipTransition);
_Layer2.Play(animationClip); 

either way , only layer2 play animation successfully

**Comment by KybernetikGames** [comment] 2022-11-15 07:57
That's by design. Both of those calls will reuse an existing `ClipState` for the given clip if there is one so you're creating a state on layer 1 then moving it to layer 2. If you want multiple states with the same clip you need to explicitly create them as demonstrated in the example.

**Comment by NiyahIsFine** [comment] 2022-11-15 08:11
tkx for exp

**Comment by KybernetikGames** [comment] 2022-11-15 08:28
Upon further consideration, the way you were expecting it to work actually makes more sense. Playing something on Layer 2 isn't supposed to affect what's playing on Layer 1 but having it steal the existing state from Layer 1 violates that rule.

I'll try to implement it so that playing on a new layer will create a new state for that layer. It will likely require a few too many changes to just post here, but if you email your Invoice Number to animancer@kybernetik.com.au I'll send you an updated Animancer package once I get it working.

**Comment by KybernetikGames** [comment] 2022-11-19 23:30
I've changed it so that your original code would work as intended.

I don't have an ETA on the next Animancer yet, but if anyone wants to try it out just let me know.

**Comment by NiyahIsFine** [comment] 2022-12-07 07:56
i have solved it by some changes

**Comment by NiyahIsFine** [comment] 2022-12-07 07:56
tkx for help

**Comment by KybernetikGames** [comment] 2022-12-09 12:56
[Animancer v7.4](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-4) is now available for Early Access and has this feature in it.

**Comment by KybernetikGames** [comment] 2023-01-26 04:19
[Animancer v7.4](https://kybernetik.com.au/animancer/docs/changes/animancer-v7-4/) is now available with this behaviour working as you originally expected it to.

**Closed by KybernetikGames** 2023-01-26 04:19 UTC
Labels: Enhancement, Solved
