### ISSUE TITLE
Pack Texture Failed at Unity Version 2023.2.20f1

### ISSUE THREAD

**Issue by q393980062** [KybernetikGames/animancer#360] opened 2024-09-17 18:13 UTC
# Environment

- Animancer Version Number: 8.0.0
- Animancer Pro or Lite: Pro
- Unity Version: 2023.2.20f1
- Platform: Windows x64

# Description

When I use Pack Texture to pack any file, I get the following error:

> Texture must have width greater than 0.
UnityEngine.Texture2D:.ctor (int,int,UnityEngine.TextureFormat,bool)
Animancer.Editor.Tools.PackTexturesTool:Pack () (at ./Packages/com.kybernetik.animancer/Editor/Animancer Tools/PackTexturesTool.cs:184)
Animancer.Editor.Tools.PackTexturesTool:DoBodyGUI () (at ./Packages/com.kybernetik.animancer/Editor/Animancer Tools/PackTexturesTool.cs:122)
Animancer.Editor.Tools.AnimancerToolsWindow/Tool:DoGUI () (at ./Packages/com.kybernetik.animancer/Editor/Animancer Tools/Tool.cs:115)
Animancer.Editor.Tools.AnimancerToolsWindow:OnGUI () (at ./Packages/com.kybernetik.animancer/Editor/Animancer Tools/AnimancerToolsWindow.cs:127)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

It seems that in the current version of Unity, creating a 0x0 texture is not allowed.

`var packedTexture = new Texture2D(0, 0, TextureFormat.ARGB32, false);`

After changing the texture size to 1x1, the Pack Texture works correctly.

`var packedTexture = new Texture2D(1, 1, TextureFormat.ARGB32, false);`

**Comment by KybernetikGames** [comment] 2024-09-18 12:08
I've confirmed the same in Unity 6. Your fix looks like the way to go so it will be in the next version of Animancer.

**Comment by KybernetikGames** [comment] 2024-11-02 15:29
[Animancer v8.0.2](http://localhost:5080/animancer/docs/changes/animancer-v8-0/#minor-updates) is now available with this fix in it.

**Closed by KybernetikGames** 2024-11-02 15:29 UTC
Labels: Bug, Solved
