### ISSUE TITLE
AnimationState questions 

### ISSUE THREAD

**Issue by kykcyawe** [KybernetikGames/animancer#167] opened 2021-11-11 14:11 UTC
What I need?
- I want to indicate different animation schemes on the character, for example, one scheme for first-person animation, another scheme for third-person animation.

Questions:
1) I think I am using AnimancerState incorrectly. Perhaps I do not fully understand what it is for?
2) Either this is a bug, or I am using Events incorrectly.
This does not work at Awake, it feels like he resets all signed events in the next frame
```
animationSchemes[i].stateJump.Events.OnEnd = PlayMove;
animationSchemes[i].Jump.Events.OnEnd = PlayMove;
```
3) For example, I will need to change and add animations from the weapon that the player is holding. When choosing a weapon, do I have to register an AnimationState for each animation first? And when the player removes the weapon then all registered AnimationState (which were added from the weapon) should I delete?

For questions 1 and 2, I made a test script

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Animancer;
using System;

public class Test : MonoBehaviour
{
    public AnimancerComponent Animancer;
    public List<AnimationScheme> animationSchemes;
    public AnimationScheme currentAnimationScheme => animationSchemes[_currentAnimationSchemeIndex];
   
    private int _currentAnimationSchemeIndex;
    private Vector2 _direction;
    private bool _jump;

    private void Awake()
    {
        for (int i = 0; i < animationSchemes.Count; i++)
        {
            animationSchemes[i].stateJump = Animancer.States.GetOrCreate(animationSchemes[i].Jump);
            animationSchemes[i].stateMove = Animancer.States.GetOrCreate(animationSchemes[i].Move) as MixerState<Vector2>;

            //This doesn't work
            animationSchemes[i].stateJump.Events.OnEnd = PlayMove;
            //or this
            animationSchemes[i].Jump.Events.OnEnd = PlayMove;
            //
        }

        PlayMove();
    }

    private void Update()
    {
        TryChangeScheme();

        GetParametres();
        SetParametres();        
    }

    private void TryChangeScheme()
    {
        if (Input.GetKeyDown(KeyCode.Tab))
        {
            _currentAnimationSchemeIndex++;

            if (_currentAnimationSchemeIndex >= animationSchemes.Count)
                _currentAnimationSchemeIndex = 0;

            PlayMove();
        }
    }

    private void GetParametres()
    {
        _direction = new Vector2();

        if (Input.GetKey(KeyCode.W))
            _direction.x = 1;
        else if (Input.GetKey(KeyCode.S))
            _direction.x = -1;

        if (Input.GetKey(KeyCode.A))
            _direction.y = 1;
        else if (Input.GetKey(KeyCode.D))
            _direction.y = -1;

        if (Input.GetKeyDown(KeyCode.Space))
            _jump = true;
    }

    private void SetParametres()
    {      
        currentAnimationScheme.stateMove.Parameter = _direction;

        if (_jump)
        {
            _jump = false;
            Animancer.Play(currentAnimationScheme.stateJump);

            //This works
            currentAnimationScheme.stateJump.Events.OnEnd = PlayMove;
            //or this
            currentAnimationScheme.Jump.Events.OnEnd = PlayMove;
            //
        }
    }

    private void PlayMove()
    {
        Animancer.Play(currentAnimationScheme.stateMove);
    }

    [Serializable]
    public class AnimationScheme
    {
        public MixerTransition2D Move;
        [HideInInspector] public MixerState<Vector2> stateMove;

        public ClipTransition Jump;
        [HideInInspector] public AnimancerState stateJump;       
    }

}

```

**Comment by KybernetikGames** [comment] 2021-11-11 21:38
This looks like it would be caused by the way events are [Cleared Automatically](https://kybernetik.com.au/animancer/docs/manual/events/animancer/behaviour#clear-automatically).

If you want to configure your events on startup, add them to the transition (not the state) and then play the transition (not the state) so that it can assign its events to the state it plays.

Also, `stateJump` is unnecessary because after calling `Animancer.States.GetOrCreate(animationSchemes[i].Jump);` the state will be accessible via `animationSchemes[i].Jump.State`.

**Closed** 2021-11-11 22:26 UTC
Labels: Question
